class AppStrings {
  static String email = "Please Enter Your Email",
      passwordHint = "Please Enter Your Password",
      forgetPassword = "Forget Password ?",
      login = "Login",
      dontHaveAccount = "Don't Have An Account ?",
      signUp = "Sign Up",
      welcomeLogin = "Welcome Again!",
      welcomeSignup = "Welcome , Sing Up To Get Our Offers!",
      fullName = "Full Name",
      haveAnAccount = "Already Have An Account ?",
      appBar = "Medical App",
      search = "Find A Doctor",
      eye = "Eyes",
      lunges = "Lunges",
      throat = "Throat",
      bones = "Bones",
      doctor1 = "Dr. Ahmed",
      doctor2 = "Dr. Muhammad",
      doctor3 = "Dr. Ali",
      doctor4 = "Dr. Khaled",
      category = "Category",
      userName = "User Name",
      changePassword = "Change Password",
      signOut = "Sign Out",
      contactUs = "Contact US",
      terms = "Terms And Conditions";
}
